#!/usr/bin/env python3
"""Evaluate post-layout validation results using GLM models.

Reads the pipeline artifacts, analyzes the pre-layout vs post-layout gap,
and uses GLM to generate an expert assessment with actionable recommendations.

Usage:
    source .env && python scripts/evaluate_postlayout.py /tmp/postlayout_v6
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# Load .env
env_path = Path(__file__).resolve().parents[1] / ".env"
if env_path.is_file():
    for line in env_path.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())


def count_net_usage(netlist_text: str) -> dict:
    """Count how many transistor terminals reference each net."""
    counts: dict[str, int] = {}
    for line in netlist_text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("X"):
            continue
        parts = stripped.split()
        # parts[0]=Xn, parts[1..4]=D,G,S,B, parts[5]=model, ...
        if len(parts) < 6:
            continue
        for net in parts[1:5]:
            counts[net] = counts.get(net, 0) + 1
    return counts


def build_analysis_prompt(results_dir: Path) -> str:
    """Build the analysis prompt from pipeline artifacts."""
    summary_path = results_dir / "postlayout_summary.json"
    summary = json.loads(summary_path.read_text())

    rcx_path = summary.get("extracted_netlist_path", "")
    rcx_text = Path(rcx_path).read_text() if rcx_path and Path(rcx_path).is_file() else ""

    # Pre-layout netlist
    pre_net = results_dir / "pre_layout" / "gf180_ota.net"
    pre_net_text = pre_net.read_text() if pre_net.is_file() else ""

    # gLayout netlist (hierarchical, generated by driver)
    glayout_net_path = results_dir / "postlayout" / "layout" / "opamp_twostage.spice"
    glayout_net_text = ""
    if glayout_net_path.is_file():
        glayout_net_text = glayout_net_path.read_text()

    # Net usage analysis
    net_counts = count_net_usage(rcx_text)
    top_nets = sorted(net_counts.items(), key=lambda x: x[1], reverse=True)[:10]

    # Count transistors by type
    n_nfet = rcx_text.count("nfet_03v3")
    n_pfet = rcx_text.count("pfet_03v3")
    n_total = n_nfet + n_pfet

    # Count transistors with all terminals on same net (shorted)
    shorted = 0
    for line in rcx_text.splitlines():
        if not line.strip().startswith("X"):
            continue
        parts = line.split()
        if len(parts) >= 5 and parts[1] == parts[2] == parts[3] == parts[4]:
            shorted += 1

    prompt = f"""You are an expert analog IC designer specializing in layout-aware design and parasitic extraction for CMOS processes.

Analyze the following post-layout validation results for a two-stage OTA on GF180MCU 180nm CMOS. The pipeline is:
  sizing -> gLayout (Python/gdsfactory) -> GDS -> Magic PEX (flat extraction) -> post-layout SPICE

## Pre-Layout Results (SPICE, schematic-level)
- Adc = 52.0 dB
- GBW = 3.87 MHz
- PM = 73.7 deg
- FoM = 6.02e+20
- Design params: {json.dumps(summary['params'])}

## Post-Layout Results
- Adc = {summary['post_Adc_dB']} dB  (delta: {summary['gain_delta_dB']:.1f} dB)
- GBW = {summary['post_GBW_Hz']}
- PM = {summary['post_PM_deg']}
- FoM = {summary['post_fom']}
- Pipeline time: {summary['total_time_s']:.0f}s (layout ~150s, PEX ~1.6s, SPICE <1s)

## Pre-Layout Schematic Netlist (correct topology, 9 transistors + caps)
```spice
{pre_net_text}
```

## Extracted Netlist Analysis (from Magic PEX flat extraction)
- Total transistors in extracted netlist: {n_total} (expected: ~9 core + dummy transistors)
- NFET: {n_nfet}, PFET: {n_pfet}
- Transistors with ALL 4 terminals on same net (shorted/useless): {shorted} / {n_total} ({100*shorted/max(n_total,1):.0f}%)
- Top net usage (net: terminal_count): {top_nets}
- Unique nets total: {len(net_counts)}
- Parasitic capacitors: {rcx_text.count(' C')} (some marked FLOATING)

## Extracted Netlist (first 30 lines + last 25 lines for caps)
```spice
{chr(10).join(rcx_text.splitlines()[:30])}
...
{chr(10).join(rcx_text.splitlines()[-25:])}
```

## gLayout-Generated Hierarchical Netlist (correct, from opamp_twostage Python)
Top subcircuit ports: VDD GND DIFFPAIR_BIAS VP VN CS_BIAS VOUT
```spice
{glayout_net_text[:3000] if glayout_net_text else '(not available)'}
```

## Architecture Context
- gLayout generates GDS via gdsfactory (Python). Cells are auto-named (hashes).
- GDS has zero net labels by default. We added 7 port labels (texttype=10) at pin locations.
- Magic flattens the entire hierarchy then extracts -- no intermediate label propagation.
- The GDS has ~120 cells, 1.5MB. Magic reads it in <2s.

## Questions for Analysis

1. **Root cause**: Why does Magic's flat extraction produce ~{shorted} transistors with all terminals shorted to VOUT? What specific mechanism causes this catastrophic net merging?

2. **Layer mapping**: gLayout/gdsfactory uses GDS layers like (22,0)=diffusion, (30,0)=poly, (33,0)=contact, (34,0)=met1, (42,0)=met3, (46,0)=met4, (81,0)=met5. Are these compatible with the GF180MCU Magic tech file? Could layer mismatches explain the extraction failure?

3. **Actionable fixes** (ranked by effort):
   a. Can we fix this by adding more internal net labels to the GDS?
   b. Should we skip flat extraction and use hierarchical extraction instead?
   c. Should we use gLayout's own netlist + add parasitic caps from a simplified PEX?
   d. Is there a better extraction tool/flow for gdsfactory-generated GDS?

4. **Architectural recommendation**: Given the current state, what is the most practical path to close the analog design loop (sizing -> layout -> verified post-layout simulation) for research/publication purposes?

Provide a structured technical analysis. Be specific about the failure mechanism and concrete about the recommended fix."""

    return prompt


def call_glm(prompt: str) -> str:
    """Call GLM model via litellm."""
    import litellm

    api_key = os.environ.get("ZAI_API_KEY")
    if not api_key:
        print("ERROR: ZAI_API_KEY not set. Source .env first.")
        sys.exit(1)

    # GLM-4.5-Flash responds in English, good reasoning
    response = litellm.completion(
        model="zai/GLM-4.5-Flash",
        messages=[{"role": "user", "content": prompt}],
        api_key=api_key,
        api_base="https://open.bigmodel.cn/api/paas/v4",
        temperature=0.3,
        max_tokens=4000,
    )
    return response.choices[0].message.content


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <results_dir>")
        print(f"Example: source .env && python {sys.argv[0]} /tmp/postlayout_v6")
        sys.exit(1)

    results_dir = Path(sys.argv[1])
    if not (results_dir / "postlayout_summary.json").is_file():
        print(f"ERROR: No postlayout_summary.json in {results_dir}")
        sys.exit(1)

    print("Building analysis prompt from pipeline artifacts...")
    prompt = build_analysis_prompt(results_dir)

    print(f"Prompt: {len(prompt)} chars")
    print("Calling GLM-4.5-Flash for expert analysis...")
    print()

    response = call_glm(prompt)

    print("=" * 70)
    print("GLM EXPERT ANALYSIS: POST-LAYOUT VALIDATION")
    print("=" * 70)
    print(response)
    print("=" * 70)

    # Save report
    report_path = results_dir / "glm_analysis.md"
    report_path.write_text(f"# GLM Expert Analysis: Post-Layout Validation\n\n{response}\n")
    print(f"\nReport saved to {report_path}")


if __name__ == "__main__":
    main()
